# This is a basic workflow to help you get started with Actions

name: Java CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.2
      uses: actions/setup-java@v1.4.2
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        java-version: '14.0.2'
        java-package: jdk+fx
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Package with Gradle
      run: ./gradlew jpackage
    - name: list directory *nix
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: |
        ls -al
    - name: list directory win
      if: matrix.os == 'windows-latest'
      run: |
        dir
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jpackage
        path: |
          build/jpackage
          !build/jpackage/whatwebfx/bin
          !build/jpackage/whatwebfx/lib
